service: lynx-services

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  LynxAuthenticationSocial:
    handler: index.authSocial
    events:
      - http:
          path: authentication/social/facebook
          method: get
      - http:
          path: authentication/social/google
          method: get
      - http:
          path: authentication/social/outlook
          method: get
      - http:
          path: authentication/social/facebook/callback
          method: get
      - http:
          path: authentication/social/google/callback
          method: get
      - http:
          path: authentication/social/outlook/callback
          method: get
plugins:
  - serverless-offline